Uploading html files
WSI2020-FloorFinder/floor-finder pull request #18
Opened 2022-04-28 18:11 UTC by mariavo1

This is the html version of all the pug files

2022-04-28 18:18 UTC, saugusth approved these changes

2022-04-28 19:51 UTC, cchang46 commented
I was wondering if we decided to use Pug why do we need these html files?

2022-04-28 19:54 UTC, h-akram approved these changes

2022-04-28 20:23 UTC, cchang46 requested changes
HTML files are not required. (The Pug views should be mapped in Express routing instead.)

2022-04-29 05:07 UTC, cchang46 approved these changes

2022-04-29 05:08 UTC, cchang46 approved these changes

2022-04-29 05:08 UTC, merged